<a href="https://colab.research.google.com/github/sun-fox/GluonCV-Mxnet/blob/master/Gluon_Blocks_Initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mxnet-cu101mkl
!pip install gluoncv

     |████████████████████████████████| 711.0MB 26kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
     |████████████████████████████████| 757kB 9.1MB/s 


In [0]:
import mxnet as mx
from mxnet import init,nd
from mxnet.gluon import nn

In [3]:
init.Uniform
init.Normal
init.Xavier
init.Zero
init.One
init.Constant

mxnet.initializer.Constant

**Xavier Initialization**

Designed to keep the scale of gradient roughly the same in all layers.
The initializer fills the weight with random numbers in the range of [-c,c],
where c = sqrt(mag/0.5*(n_in + n_out))


In [4]:
layer = nn.Conv2D(channels=1,in_channels=1, kernel_size=(3,3))
layer.initialize(init.Xavier())
layer.weight.data()


[[[[ 0.05636501  0.10720772  0.24847925]
   [ 0.39752382  0.11866093  0.41332   ]
   [ 0.05182666  0.4009717  -0.08815584]]]]
<NDArray 1x1x3x3 @cpu(0)>

In [5]:
layer = nn.Conv2D(channels=512,in_channels=512, kernel_size=(3,3))
layer.initialize(init.Xavier())
layer.weight.data()[0]


[[[ 0.00630558  0.00744513 -0.00590012]
  [-0.00318499 -0.01033202  0.01999258]
  [-0.0226214   0.02366119 -0.01160159]]

 [[-0.0059481  -0.00113977  0.01488703]
  [ 0.01593029  0.00147454 -0.00102179]
  [ 0.00347238 -0.0054713   0.02171864]]

 [[ 0.01715045 -0.02189048 -0.00829784]
  [-0.02106922  0.00756137 -0.02448375]
  [-0.00672377  0.01697394  0.0233291 ]]

 ...

 [[-0.01893761  0.01284147 -0.00975751]
  [-0.02142992 -0.00148998 -0.00093406]
  [ 0.00985651 -0.00277236  0.00710726]]

 [[ 0.00880146 -0.01043105 -0.00261599]
  [-0.00773894  0.01042632 -0.01882804]
  [ 0.00926955  0.00075613  0.01006069]]

 [[ 0.00549796  0.00605232 -0.0150173 ]
  [-0.01781082  0.02513626  0.01330902]
  [-0.01826004  0.01434206  0.0111638 ]]]
<NDArray 512x3x3 @cpu(0)>

**Defered Initialization**

In [6]:
layer = nn.Conv2D(channels=1, kernel_size=(3,3))
layer.weight

Parameter conv2_weight (shape=(1, 0, 3, 3), dtype=<class 'numpy.float32'>)

In [7]:
layer.initialize(init.Xavier())
layer(mx.nd.ones((1,8,224,224)))
layer.weight

Parameter conv2_weight (shape=(1, 8, 3, 3), dtype=<class 'numpy.float32'>)

**Initialization Context**

In [0]:
layer = nn.Conv2D(channels=1, kernel_size=(3,3))
layer.initialize(init.Xavier(), ctx=mx.gpu())

In [9]:
layer(nd.uniform(shape=(1,3,9,9), ctx=mx.gpu()))


[[[[1.2898028  1.110988   1.137672   1.2746624  1.1320616  1.2411841
    1.2996763 ]
   [2.0227969  1.3626624  1.6164691  1.1885686  1.0964382  1.2469984
    1.2867093 ]
   [1.0631251  1.9179451  1.6159045  1.0920229  1.2020497  1.6726247
    1.4360905 ]
   [1.2220917  1.5597315  1.4766033  1.0448022  1.4664203  1.4242986
    1.2903199 ]
   [1.3970885  1.4029529  1.306343   1.7303979  1.3930414  1.5824035
    1.509001  ]
   [0.8560147  1.5070189  1.107607   1.003307   0.3736256  1.3860799
    0.8027376 ]
   [1.90825    1.4922979  1.6973102  0.58472186 1.6751751  2.2057414
    1.1906272 ]]]]
<NDArray 1x1x7x7 @gpu(0)>

**Set Data**

In [10]:
layer.weight.set_data(nd.ones((1,3,3,3),ctx=mx.gpu()))
layer.weight.data()


[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
<NDArray 1x3x3x3 @gpu(0)>